models:
  - name: customers_stg
    columns:
      - name: Email
        tests:
           - string_not_empty

  - name: orders_stg
    columns:
      - name: OrderID
        tests:
           - unique
           - not_null

      - name: StatusCD
        tests:
           - accepted_values:
              values: ['Shipped', 'Delivered', 'Processing', 'Cancelled', 'Pending']

  
